modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MoriyaShiine/crashma/issues"
[[mods]]
modId="crashma"
version="${file.jarVersion}"
displayName="Crashma"
displayURL="https://www.curseforge.com/minecraft/mc-mods/crashma"
logoFile="icon.png"
authors="MoriyaShiine"
description='''
What's Crashma, you ask? Crashma game LOL'''
[[dependencies.crashma]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.crashma]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
