modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory
issueTrackerURL="https://github.com/MoriyaShiine/crashma/issues" #optional
[[mods]] #mandatory
modId="crashma" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Crashma" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/crashma" #optional
authors="MoriyaShiine" #optional
description='''What's Crashma, you ask? Crashma game LOL'''
[[dependencies.crashma]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.crashma]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.1]"
    ordering="NONE"
    side="BOTH"