name: Issue
description: File a bug report
body:
  - type: input
    attributes:
      label: Mod version (NOT Minecraft version)
      description: Please note that unless this bug still exists on the latest avaiable Mod version and Minecraft version, it will not be fixed. Versions titled "latest,", "newest," or some other vague indiciator will be closed without comment.
    validations:
      required: true
  - type: textarea
    attributes:
      label: A description of the issue
    validations:
      required: true
  - type: input
    attributes:
      label: Log or crash report
      description: Please use [gist](https://gist.github.com/).
    validations:
      required: true
